name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  setup:
    name: Install & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run test:unit
      - run: npm run test:integration
      #e2e tests are run in a separate job to ensure the server is running before the tests are executed
      - name: Run System Tests (Cypress)
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          command: npm run test:e2e
          wait-on: 'http://localhost:5173'